force-app/main/default/objects/Job_Certification_Requirement__c/Job_Certification_Requirement__c.object-meta.xml
<CustomObject>
    <label>Certification Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Certification Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Certification_Name__c.field-meta.xml
<CustomField>
    <fullName>Certification_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Certification_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Certification Requirements</relationshipLabel>
    <relationshipName>Certification_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/Job_Clinical_Skill__c.object-meta.xml
<CustomObject>
    <label>Job_Clinical_Skill</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Clinical_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Clinical_Skill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Clinical_Skill</relationshipLabel>
    <relationshipName>Job_Clinical_Skill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <label>Skill_Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Skill_Name__c.field-meta.xml
<CustomField>
    <fullName>Skill_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Skill_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Compliance_Requirement__c/Job_Compliance_Requirement__c.object-meta.xml
<CustomObject>
    <label>Job_Compliance_Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Compliance_Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Compliance_Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Compliance_Requirement__c/fields/Compliance_Name__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Compliance_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Compliance_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Compliance_Requirements</relationshipLabel>
    <relationshipName>Job_Compliance_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Education_Requirement__c/Job_Education_Requirement__c.object-meta.xml
<CustomObject>
    <label>Education Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Education Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Education_Requirement__c/fields/Degree_Name__c.field-meta.xml
<CustomField>
    <fullName>Degree_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Degree_Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Education_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Education Requirements</relationshipLabel>
    <relationshipName>Education_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/Job_License_Requirement__c.object-meta.xml
<CustomObject>
    <label>License Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_License_Requirement__c/fields/Active_Required__c.field-meta.xml
<CustomField>
    <fullName>Active_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active_Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/Expiry_Check_Required__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Check_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expiry_Check_Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/Issuing_Authority__c.field-meta.xml
<CustomField>
    <fullName>Issuing_Authority__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issuing_Authority</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>License Requirements</relationshipLabel>
    <relationshipName>License_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>License_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job_Posting</label>
    <nameField>
        <label>Job_Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Credentialing_Required__c.field-meta.xml
<CustomField>
    <fullName>Credentialing_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Credentialing Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>ICU</fullName>
            </value>
            <value>
                <fullName>Lab</fullName>
            </value>
            <value>
                <fullName>OPD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Facility Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Job Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Max_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Max_Experience_Years__c</fullName>
    <label>Max Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Min_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Min_Experience_Years__c</fullName>
    <label>Min Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Privilege_Scope__c.field-meta.xml
<CustomField>
    <fullName>Privilege_Scope__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Privilege Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <label>Role Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Paramedic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Shift_Type__c.field-meta.xml
<CustomField>
    <fullName>Shift_Type__c</fullName>
    <label>Shift Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Night</fullName>
            </value>
            <value>
                <fullName>Rotational</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/Job_Procedure_Requirement__c.object-meta.xml
<CustomObject>
    <label>Job_Procedure_Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Procedure_Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Procedure_Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Critical__c.field-meta.xml
<CustomField>
    <fullName>Critical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Critical</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Procedure_Requirements</relationshipLabel>
    <relationshipName>Job_Procedure_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Procedure_Name__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Procedure_Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AIJobPostingServiceTest.cls
@IsTest
private class AIJobPostingServiceTest {

    // ---------------------------------------------------------------------
    // Helper to build a full AI data structure as parseAIResponse would return
    // ---------------------------------------------------------------------
    private static Map<String, Object> buildFullAIData() {
        Map<String, Object> jobPosting = new Map<String, Object>{
            'Job_Title__c'             => 'Consultant Cardiologist',
            'Description__c'           => 'Provide comprehensive cardiac care',
            'Category__c'              => 'Medical',
            'Role_Type__c'             => 'Doctor',
            'Department__c'            => 'Emergency',
            'Employment_Type__c'       => 'Full-time',
            'Shift_Type__c'            => 'Day',
            'Min_Experience_Years__c'  => 2,
            'Max_Experience_Years__c'  => 10,
            'Start_Date__c'            => '2026-02-01',
            'End_Date__c'              => '2026-04-01',
            'Facility_Name__c'         => 'City Hospital',
            'City__c'                  => 'San Francisco',
            'State__c'                 => 'CA',
            'Country__c'               => 'USA',
            'Credentialing_Required__c'=> true,
            'Privilege_Scope__c'       => 'Full cardiology privileges'
        };

        List<Object> educationRequirements = new List<Object>{
            new Map<String, Object>{
                'Degree_Name__c' => 'MBBS',
                'Mandatory__c'   => true
            }
        };

        List<Object> licenseRequirements = new List<Object>{
            new Map<String, Object>{
                'License_Name__c'          => 'Medical Council Registration',
                'Issuing_Authority__c'     => 'Medical Council of USA',
                'Active_Required__c'       => true,
                'Expiry_Check_Required__c' => true
            }
        };

        List<Object> certificationRequirements = new List<Object>{
            new Map<String, Object>{
                'Certification_Name__c' => 'BLS',
                'Mandatory__c'          => true
            }
        };

        List<Object> clinicalSkills = new List<Object>{
            new Map<String, Object>{
                'Skill_Name__c'  => 'ECG Interpretation',
                'Skill_Level__c' => 'Advanced',
                'Mandatory__c'   => true
            }
        };

        List<Object> procedureRequirements = new List<Object>{
            new Map<String, Object>{
                'Procedure_Name__c' => 'IV Cannulation',
                'Critical__c'       => true
            }
        };

        List<Object> complianceRequirements = new List<Object>{
            new Map<String, Object>{
                'Compliance_Name__c' => 'HIPAA',
                'Mandatory__c'       => true
            }
        };

        Map<String, Object> aiData = new Map<String, Object>();
        aiData.put('jobPosting', jobPosting);
        aiData.put('educationRequirements', educationRequirements);
        aiData.put('licenseRequirements', licenseRequirements);
        aiData.put('certificationRequirements', certificationRequirements);
        aiData.put('clinicalSkills', clinicalSkills);
        aiData.put('procedureRequirements', procedureRequirements);
        aiData.put('complianceRequirements', complianceRequirements);

        return aiData;
    }

    // ---------------------------------------------------------------------
    // Test: Successful creation of comprehensive job posting (main + children)
    // ---------------------------------------------------------------------
    @IsTest
    static void testCreateComprehensiveJobPosting_FullData() {
        Map<String, Object> aiData = buildFullAIData();

        Test.startTest();
        String jobPostingId = AIJobPostingService.createComprehensiveJobPosting(aiData);
        Test.stopTest();

        System.assertNotEquals(null, jobPostingId, 'Job Posting Id should not be null');

        // Verify main Job_Posting__c record
        Job_Posting__c jp = [
            SELECT Job_Title__c, Description__c, Category__c, Role_Type__c,
                   Department__c, Employment_Type__c, Shift_Type__c,
                   Min_Experience_Years__c, Max_Experience_Years__c,
                   Start_Date__c, End_Date__c,
                   Facility_Name__c, City__c, State__c, Country__c,
                   Credentialing_Required__c, Privilege_Scope__c
            FROM Job_Posting__c
            WHERE Id = :jobPostingId
        ];

        System.assertEquals('Consultant Cardiologist', jp.Job_Title__c);
        System.assertEquals('Provide comprehensive cardiac care', jp.Description__c);
        System.assertEquals('Medical', jp.Category__c);
        System.assertEquals('Doctor', jp.Role_Type__c);
        System.assertEquals('Emergency', jp.Department__c);
        System.assertEquals('Full-time', jp.Employment_Type__c);
        System.assertEquals('Day', jp.Shift_Type__c);
        System.assertEquals(2, jp.Min_Experience_Years__c);
        System.assertEquals(10, jp.Max_Experience_Years__c);
        System.assertEquals(Date.newInstance(2026, 2, 1), jp.Start_Date__c);
        System.assertEquals(Date.newInstance(2026, 4, 1), jp.End_Date__c);
        System.assertEquals('City Hospital', jp.Facility_Name__c);
        System.assertEquals('San Francisco', jp.City__c);
        System.assertEquals('CA', jp.State__c);
        System.assertEquals('USA', jp.Country__c);
        System.assertEquals(true, jp.Credentialing_Required__c);
        System.assertEquals('Full cardiology privileges', jp.Privilege_Scope__c);

        // Verify child records

        // Education
        List<Job_Education_Requirement__c> edu = [
            SELECT Job_Posting__c, Degree_Name__c, Mandatory__c
            FROM Job_Education_Requirement__c
            WHERE Job_Posting__c = :jobPostingId
        ];
        System.assertEquals(1, edu.size(), 'One education requirement expected');
        System.assertEquals('MBBS', edu[0].Degree_Name__c);
        System.assertEquals(true, edu[0].Mandatory__c);

        // License
        List<Job_License_Requirement__c> lic = [
            SELECT License_Name__c, Issuing_Authority__c,
                   Active_Required__c, Expiry_Check_Required__c
            FROM Job_License_Requirement__c
            WHERE Job_Posting__c = :jobPostingId
        ];
        System.assertEquals(1, lic.size(), 'One license requirement expected');
        System.assertEquals('Medical Council Registration', lic[0].License_Name__c);
        System.assertEquals('Medical Council of USA', lic[0].Issuing_Authority__c);
        System.assertEquals(true, lic[0].Active_Required__c);
        System.assertEquals(true, lic[0].Expiry_Check_Required__c);

        // Certification
        List<Job_Certification_Requirement__c> certs = [
            SELECT Certification_Name__c, Mandatory__c
            FROM Job_Certification_Requirement__c
            WHERE Job_Posting__c = :jobPostingId
        ];
        System.assertEquals(1, certs.size(), 'One certification requirement expected');
        System.assertEquals('BLS', certs[0].Certification_Name__c);
        System.assertEquals(true, certs[0].Mandatory__c);

        // Clinical skills
        List<Job_Clinical_Skill__c> skills = [
            SELECT Skill_Name__c, Skill_Level__c, Mandatory__c
            FROM Job_Clinical_Skill__c
            WHERE Job_Posting__c = :jobPostingId
        ];
        System.assertEquals(1, skills.size(), 'One clinical skill expected');
        System.assertEquals('ECG Interpretation', skills[0].Skill_Name__c);
        System.assertEquals('Advanced', skills[0].Skill_Level__c);
        System.assertEquals(true, skills[0].Mandatory__c);

        // Procedures
        List<Job_Procedure_Requirement__c> procs = [
            SELECT Procedure_Name__c, Critical__c
            FROM Job_Procedure_Requirement__c
            WHERE Job_Posting__c = :jobPostingId
        ];
        System.assertEquals(1, procs.size(), 'One procedure requirement expected');
        System.assertEquals('IV Cannulation', procs[0].Procedure_Name__c);
        System.assertEquals(true, procs[0].Critical__c);

        // Compliance
        List<Job_Compliance_Requirement__c> comps = [
            SELECT Compliance_Name__c, Mandatory__c
            FROM Job_Compliance_Requirement__c
            WHERE Job_Posting__c = :jobPostingId
        ];
        System.assertEquals(1, comps.size(), 'One compliance requirement expected');
        System.assertEquals('HIPAA', comps[0].Compliance_Name__c);
        System.assertEquals(true, comps[0].Mandatory__c);
    }

    // ---------------------------------------------------------------------
    // Test: Defaults and missing optional child lists
    // ---------------------------------------------------------------------
    @IsTest
    static void testCreateComprehensiveJobPosting_DefaultsAndNoChildren() {
        // jobPosting with minimal required plus some missing fields to trigger defaults
        Map<String, Object> jobPosting = new Map<String, Object>{
            'Job_Title__c'       => 'Staff Nurse',
            'Category__c'        => null,        // should default to Medical
            'Role_Type__c'       => 'Nurse',
            'Employment_Type__c' => null,        // should default to Full-time
            'Facility_Name__c'   => 'General Hospital',
            'City__c'            => 'Boston',
            'State__c'           => 'MA',
            'Country__c'         => 'USA',
            'Start_Date__c'      => null,        // should default to today + 30
            'Min_Experience_Years__c' => null,
            'Max_Experience_Years__c' => null,
            'Credentialing_Required__c' => null  // should use default false
        };

        Map<String, Object> aiData = new Map<String, Object>{
            'jobPosting'             => jobPosting,
            'educationRequirements'  => new List<Object>(),
            'licenseRequirements'    => new List<Object>(),
            'certificationRequirements' => new List<Object>(),
            'clinicalSkills'         => new List<Object>(),
            'procedureRequirements'  => new List<Object>(),
            'complianceRequirements' => new List<Object>()
        };

        Date todayPlus30 = Date.today().addDays(30);

        Test.startTest();
        String jobPostingId = AIJobPostingService.createComprehensiveJobPosting(aiData);
        Test.stopTest();

        Job_Posting__c jp = [
            SELECT Job_Title__c, Category__c, Role_Type__c, Employment_Type__c,
                   Facility_Name__c, City__c, State__c, Country__c,
                   Start_Date__c, Min_Experience_Years__c, Max_Experience_Years__c,
                   Credentialing_Required__c
            FROM Job_Posting__c
            WHERE Id = :jobPostingId
        ];

        System.assertEquals('Staff Nurse', jp.Job_Title__c);
        System.assertEquals('Medical', jp.Category__c, 'Category should default to Medical');
        System.assertEquals('Nurse', jp.Role_Type__c);
        System.assertEquals('Full-time', jp.Employment_Type__c, 'Employment type should default to Full-time');
        System.assertEquals('General Hospital', jp.Facility_Name__c);
        System.assertEquals('Boston', jp.City__c);
        System.assertEquals('MA', jp.State__c);
        System.assertEquals('USA', jp.Country__c);
        System.assertEquals(todayPlus30, jp.Start_Date__c, 'Start date should default to today + 30 days');
        System.assertEquals(null, jp.Min_Experience_Years__c);
        System.assertEquals(null, jp.Max_Experience_Years__c);
        System.assertEquals(false, jp.Credentialing_Required__c, 'Should use default false');

        // No child records expected
        System.assertEquals(0, [SELECT COUNT() FROM Job_Education_Requirement__c WHERE Job_Posting__c = :jobPostingId]);
        System.assertEquals(0, [SELECT COUNT() FROM Job_License_Requirement__c   WHERE Job_Posting__c = :jobPostingId]);
        System.assertEquals(0, [SELECT COUNT() FROM Job_Certification_Requirement__c WHERE Job_Posting__c = :jobPostingId]);
        System.assertEquals(0, [SELECT COUNT() FROM Job_Clinical_Skill__c        WHERE Job_Posting__c = :jobPostingId]);
        System.assertEquals(0, [SELECT COUNT() FROM Job_Procedure_Requirement__c WHERE Job_Posting__c = :jobPostingId]);
        System.assertEquals(0, [SELECT COUNT() FROM Job_Compliance_Requirement__c WHERE Job_Posting__c = :jobPostingId]);
    }

    // ---------------------------------------------------------------------
    // Test: Validation error path (missing required fields) and rollback
    // ---------------------------------------------------------------------
    @IsTest
    static void testCreateComprehensiveJobPosting_MissingRequired() {
        // Missing Job_Title__c -> should throw CalloutException and rollback
        Map<String, Object> jobPosting = new Map<String, Object>{
            // 'Job_Title__c' missing
            'Category__c'        => 'Medical',
            'Role_Type__c'       => 'Doctor',
            'Employment_Type__c' => 'Full-time',
            'Facility_Name__c'   => 'City Hospital',
            'City__c'            => 'San Francisco',
            'State__c'           => 'CA',
            'Country__c'         => 'USA'
        };

        Map<String, Object> aiData = new Map<String, Object>{
            'jobPosting' => jobPosting
        };

        Integer beforeCount = [SELECT COUNT() FROM Job_Posting__c];
        Boolean exceptionThrown = false;

        try {
            Test.startTest();
            AIJobPostingService.createComprehensiveJobPosting(aiData);
            Test.stopTest();
        } catch (CalloutException e) {
            exceptionThrown = true;
            System.assert(
                e.getMessage().contains('Job Title is required'),
                'Exception message should mention Job Title'
            );
        }

        System.assertEquals(true, exceptionThrown, 'Expected CalloutException to be thrown');

        Integer afterCount = [SELECT COUNT() FROM Job_Posting__c];
        System.assertEquals(
            beforeCount,
            afterCount,
            'No Job_Posting__c records should have been inserted due to rollback'
        );
    }

    // ---------------------------------------------------------------------
    // Test: Helper methods getString, getDate, getDecimal, getBoolean
    // ---------------------------------------------------------------------
    @IsTest
    static void testHelperMethods() {
        Map<String, Object> data = new Map<String, Object>{
            'stringKey'   => ' Test String ',
            'nullString'  => 'null',
            'dateKey'     => '2026-02-01',
            'badDate'     => '2026/02/01',
            'decimalKey'  => '123.45',
            'badDecimal'  => 'abc',
            'boolTrue1'   => true,
            'boolTrue2'   => 'Yes',
            'boolFalse1'  => false,
            'boolFalse2'  => '0',
            'boolUnknown' => 'maybe'
        };

        // getString
        System.assertEquals('Test String', AIJobPostingService.getString(data, 'stringKey'));
        System.assertEquals(null, AIJobPostingService.getString(data, 'nullString'));

        // getDate
        Date d = AIJobPostingService.getDate(data, 'dateKey');
        System.assertEquals(Date.newInstance(2026, 2, 1), d);
        System.assertEquals(null, AIJobPostingService.getDate(data, 'badDate'));

        // getDecimal
        Decimal dec = AIJobPostingService.getDecimal(data, 'decimalKey');
        System.assertEquals(123.45, dec);
        System.assertEquals(null, AIJobPostingService.getDecimal(data, 'badDecimal'));

        // getBoolean
        System.assertEquals(true,  AIJobPostingService.getBoolean(data, 'boolTrue1', false));
        System.assertEquals(true,  AIJobPostingService.getBoolean(data, 'boolTrue2', false));
        System.assertEquals(false, AIJobPostingService.getBoolean(data, 'boolFalse1', true));
        System.assertEquals(false, AIJobPostingService.getBoolean(data, 'boolFalse2', true));
        // unknown value -> default
        System.assertEquals(true,  AIJobPostingService.getBoolean(data, 'boolUnknown', true));
    }

    // ---------------------------------------------------------------------
    // Test: processNLPInput with mocked Gemini response
    // ---------------------------------------------------------------------
    @IsTest
    static void testProcessNLPInput_Success() {
        Test.setMock(HttpCalloutMock.class, new GeminiApiMock());

        Test.startTest();
        Map<String, Object> result = AIJobPostingService.processNLPInput(
            'We need a Consultant Cardiologist in San Francisco.'
        );
        Test.stopTest();

        System.assertNotEquals(null, result, 'Result map should not be null');
        System.assert(result.containsKey('jobPosting'), 'Result should contain jobPosting key');

        Map<String, Object> jobPosting = (Map<String, Object>) result.get('jobPosting');
        System.assertEquals('Consultant Cardiologist', jobPosting.get('Job_Title__c'));
        System.assertEquals('Medical', jobPosting.get('Category__c'));
        System.assertEquals('Doctor', jobPosting.get('Role_Type__c'));
        System.assertEquals('San Francisco', jobPosting.get('City__c'));
    }

    // ---------------------------------------------------------------------
    // Test: testGeminiConnection with mocked Gemini response
    // ---------------------------------------------------------------------
    @IsTest
    static void testTestGeminiConnection() {
        Test.setMock(HttpCalloutMock.class, new GeminiApiMock());

        Test.startTest();
        String result = AIJobPostingService.testGeminiConnection();
        Test.stopTest();

        System.assertNotEquals(null, result, 'Result string should not be null');
        System.assert(
            result.startsWith('Gemini Test Result:') ||
            result.startsWith('Gemini Test Error:'),
            'Result should be prefixed by Gemini Test Result/Error'
        );
    }

    // ---------------------------------------------------------------------
    // HttpCalloutMock for Gemini API
    // This is designed to match what GeminiAPIService.extractContent expects:
    //  body.candidates[0].content.parts[0].text contains the JSON string.
    // ---------------------------------------------------------------------
    private class GeminiApiMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setHeader('Content-Type', 'application/json');

            // Inner JSON exactly as AIJobPostingService expects (jobPosting + child arrays)
            String innerJson =
                '{' +
                    '"jobPosting":{' +
                        '"Job_Title__c":"Consultant Cardiologist",' +
                        '"Description__c":"Provide comprehensive cardiac care",' +
                        '"Category__c":"Medical",' +
                        '"Role_Type__c":"Doctor",' +
                        '"Employment_Type__c":"Full-time",' +
                        '"Facility_Name__c":"City Hospital",' +
                        '"City__c":"San Francisco",' +
                        '"State__c":"CA",' +
                        '"Country__c":"USA",' +
                        '"Start_Date__c":"2026-02-01",' +
                        '"End_Date__c":"2026-04-01"' +
                    '},' +
                    '"educationRequirements":[{"Degree_Name__c":"MBBS","Mandatory__c":true}],' +
                    '"licenseRequirements":[{"License_Name__c":"Medical Council Registration","Issuing_Authority__c":"Medical Council of USA","Active_Required__c":true,"Expiry_Check_Required__c":true}],' +
                    '"certificationRequirements":[{"Certification_Name__c":"BLS","Mandatory__c":true}],' +
                    '"clinicalSkills":[{"Skill_Name__c":"ECG Interpretation","Skill_Level__c":"Advanced","Mandatory__c":true}],' +
                    '"procedureRequirements":[{"Procedure_Name__c":"IV Cannulation","Critical__c":true}],' +
                    '"complianceRequirements":[{"Compliance_Name__c":"HIPAA","Mandatory__c":true}]' +
                '}';

            // Gemini-style wrapper response
            String body =
                '{' +
                    '"candidates":[{' +
                        '"content":{"parts":[{' +
                            '"text":"' + innerJson.replace('"', '\\"') + '"' +
                        '}]}' +
                    '}],' +
                    '"modelVersion":"test-model"' +
                '}';

            res.setBody(body);
            return res;
        }
    }
}