force-app/main/default/objects/Job_Certification_Requirement__c/Job_Certification_Requirement__c.object-meta.xml
<CustomObject>
    <label>Certification Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Certification Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Certification_Name__c.field-meta.xml
<CustomField>
    <fullName>Certification_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Certification_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Certification Requirements</relationshipLabel>
    <relationshipName>Certification_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/Job_Clinical_Skill__c.object-meta.xml
<CustomObject>
    <label>Job_Clinical_Skill</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Clinical_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Clinical_Skill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Clinical_Skill</relationshipLabel>
    <relationshipName>Job_Clinical_Skill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <label>Skill_Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Skill_Name__c.field-meta.xml
<CustomField>
    <fullName>Skill_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Skill_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Compliance_Requirement__c/Job_Compliance_Requirement__c.object-meta.xml
<CustomObject>
    <label>Job_Compliance_Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Compliance_Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Compliance_Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Compliance_Requirement__c/fields/Compliance_Name__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Compliance_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Compliance_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Compliance_Requirements</relationshipLabel>
    <relationshipName>Job_Compliance_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Education_Requirement__c/Job_Education_Requirement__c.object-meta.xml
<CustomObject>
    <label>Education Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Education Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Education_Requirement__c/fields/Degree_Name__c.field-meta.xml
<CustomField>
    <fullName>Degree_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Degree_Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Education_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Education Requirements</relationshipLabel>
    <relationshipName>Education_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/Job_License_Requirement__c.object-meta.xml
<CustomObject>
    <label>License Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_License_Requirement__c/fields/Active_Required__c.field-meta.xml
<CustomField>
    <fullName>Active_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active_Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/Expiry_Check_Required__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Check_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expiry_Check_Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/Issuing_Authority__c.field-meta.xml
<CustomField>
    <fullName>Issuing_Authority__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Issuing_Authority</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>License Requirements</relationshipLabel>
    <relationshipName>License_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>License_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job_Posting</label>
    <nameField>
        <label>Job_Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Credentialing_Required__c.field-meta.xml
<CustomField>
    <fullName>Credentialing_Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Credentialing Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>ICU</fullName>
            </value>
            <value>
                <fullName>Lab</fullName>
            </value>
            <value>
                <fullName>OPD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Facility Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Job Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Max_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Max_Experience_Years__c</fullName>
    <label>Max Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Min_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Min_Experience_Years__c</fullName>
    <label>Min Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Privilege_Scope__c.field-meta.xml
<CustomField>
    <fullName>Privilege_Scope__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Privilege Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <label>Role Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Paramedic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Shift_Type__c.field-meta.xml
<CustomField>
    <fullName>Shift_Type__c</fullName>
    <label>Shift Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Night</fullName>
            </value>
            <value>
                <fullName>Rotational</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/Job_Procedure_Requirement__c.object-meta.xml
<CustomObject>
    <label>Job_Procedure_Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Procedure_Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Procedure_Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Critical__c.field-meta.xml
<CustomField>
    <fullName>Critical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Critical</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Procedure_Requirements</relationshipLabel>
    <relationshipName>Job_Procedure_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Procedure_Name__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Procedure_Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobPostingAdminControllerTest.cls
@IsTest
private class JobPostingAdminControllerTest {
    private static String firstPicklistValue(String fieldName) {
        List<Map<String, String>> options = JobPostingAdminController.getPicklistValues(fieldName);
        return options.isEmpty() ? null : options[0].get('value');
    }

    private static String buildSavePayload() {
        String category = firstPicklistValue('Category__c');
        String roleType = firstPicklistValue('Role_Type__c');
        String dept = firstPicklistValue('Department__c');
        String empType = firstPicklistValue('Employment_Type__c');
        String shift = firstPicklistValue('Shift_Type__c');

        Map<String, Object> payload = new Map<String, Object>{
            'jobPosting' => new Map<String, Object>{
                'Job_Title__c' => 'Admin Test Job',
                'Description__c' => 'Testing admin controller',
                'Category__c' => category,
                'Role_Type__c' => roleType,
                'Department__c' => dept,
                'Employment_Type__c' => empType,
                'Shift_Type__c' => shift,
                'Min_Experience_Years__c' => 2,
                'Max_Experience_Years__c' => 5,
                'Start_Date__c' => String.valueOf(Date.today()),
                'End_Date__c' => String.valueOf(Date.today().addDays(30)),
                'Facility_Name__c' => 'Main Facility',
                'City__c' => 'Austin',
                'State__c' => 'TX',
                'Country__c' => 'USA',
                'Credentialing_Required__c' => true,
                'Privilege_Scope__c' => 'General'
            },
            'educationRequirements' => new List<Object>{
                new Map<String, Object>{ 'Degree_Name__c' => 'MBBS', 'Mandatory__c' => true }
            },
            'licenseRequirements' => new List<Object>{
                new Map<String, Object>{
                    'License_Name__c' => 'State License',
                    'Issuing_Authority__c' => 'State Board',
                    'Active_Required__c' => true,
                    'Expiry_Check_Required__c' => true
                }
            },
            'certificationRequirements' => new List<Object>{
                new Map<String, Object>{ 'Certification_Name__c' => 'ACLS', 'Mandatory__c' => true }
            },
            'clinicalSkills' => new List<Object>{
                new Map<String, Object>{ 'Skill_Name__c' => 'Critical Care', 'Skill_Level__c' => 'Advanced', 'Mandatory__c' => true }
            },
            'procedureRequirements' => new List<Object>{
                new Map<String, Object>{ 'Procedure_Name__c' => 'Intubation', 'Critical__c' => true }
            },
            'complianceRequirements' => new List<Object>{
                new Map<String, Object>{ 'Compliance_Name__c' => 'HIPAA', 'Mandatory__c' => true }
            }
        };

        return JSON.serialize(payload);
    }

    @IsTest
    static void testSaveReadUpdateDeleteAndPicklists() {
        String payload = buildSavePayload();

        Test.startTest();
        String jobId = JobPostingAdminController.saveJobPosting(payload);
        List<Job_Posting__c> allJobs = JobPostingAdminController.getJobPostings();
        List<Job_Posting__c> recent = JobPostingAdminController.getRecentJobPostings();
        Map<String, Object> details = JobPostingAdminController.getJobPostingWithDetails(jobId);
        Test.stopTest();

        System.assert(String.isNotBlank(jobId));
        System.assert(!allJobs.isEmpty());
        System.assert(!recent.isEmpty());
        System.assertNotEquals(null, details.get('jobPosting'));

        System.assertEquals(1, [SELECT Count() FROM Job_Education_Requirement__c WHERE Job_Posting__c = :jobId]);
        System.assertEquals(1, [SELECT Count() FROM Job_License_Requirement__c WHERE Job_Posting__c = :jobId]);
        System.assertEquals(1, [SELECT Count() FROM Job_Certification_Requirement__c WHERE Job_Posting__c = :jobId]);
        System.assertEquals(1, [SELECT Count() FROM Job_Clinical_Skill__c WHERE Job_Posting__c = :jobId]);
        System.assertEquals(1, [SELECT Count() FROM Job_Procedure_Requirement__c WHERE Job_Posting__c = :jobId]);
        System.assertEquals(1, [SELECT Count() FROM Job_Compliance_Requirement__c WHERE Job_Posting__c = :jobId]);

        String updatePayload = JSON.serialize(new Map<String, Object>{
            'Id' => jobId,
            'Job_Title__c' => 'Admin Test Job Updated',
            'City__c' => 'Dallas',
            'Min_Experience_Years__c' => 3,
            'Max_Experience_Years__c' => 7,
            'Start_Date__c' => String.valueOf(Date.today().addDays(1)),
            'End_Date__c' => String.valueOf(Date.today().addDays(45)),
            'Description__c' => 'Updated description'
        });

        String updateResult = JobPostingAdminController.updateJobPosting(updatePayload);
        System.assertEquals('Success', updateResult);

        Job_Posting__c updated = [
            SELECT Job_Title__c, City__c, Min_Experience_Years__c, Max_Experience_Years__c
            FROM Job_Posting__c
            WHERE Id = :jobId
        ];
        System.assertEquals('Admin Test Job Updated', updated.Job_Title__c);
        System.assertEquals('Dallas', updated.City__c);
        System.assertEquals(3, updated.Min_Experience_Years__c);
        System.assertEquals(7, updated.Max_Experience_Years__c);

        JobPostingAdminController.deleteJobPosting(jobId);
        System.assertEquals(0, [SELECT Count() FROM Job_Posting__c WHERE Id = :jobId]);
    }

    @IsTest
    static void testValidationAndErrorPaths() {
        try {
            JobPostingAdminController.saveJobPosting('');
            System.assert(false, 'Expected save validation exception');
        } catch (AuraHandledException e) {
            System.assert(true);
        }

        try {
            JobPostingAdminController.getPicklistValues('Bad_Field__c');
            System.assert(false, 'Expected invalid field exception');
        } catch (AuraHandledException e) {
            System.assert(true);
        }

        try {
            JobPostingAdminController.deleteJobPosting(null);
            System.assert(false, 'Expected null id exception');
        } catch (AuraHandledException e) {
            System.assert(true);
        }

        String category = firstPicklistValue('Category__c');
        String roleType = firstPicklistValue('Role_Type__c');
        String empType = firstPicklistValue('Employment_Type__c');

        String badDatesPayload = JSON.serialize(new Map<String, Object>{
            'jobPosting' => new Map<String, Object>{
                'Job_Title__c' => 'Bad Dates Job',
                'Category__c' => category,
                'Role_Type__c' => roleType,
                'Employment_Type__c' => empType,
                'Facility_Name__c' => 'Main Facility',
                'City__c' => 'Austin',
                'State__c' => 'TX',
                'Country__c' => 'USA',
                'Start_Date__c' => String.valueOf(Date.today().addDays(10)),
                'End_Date__c' => String.valueOf(Date.today())
            },
            'educationRequirements' => new List<Object>(),
            'licenseRequirements' => new List<Object>(),
            'certificationRequirements' => new List<Object>(),
            'clinicalSkills' => new List<Object>(),
            'procedureRequirements' => new List<Object>(),
            'complianceRequirements' => new List<Object>()
        });

        try {
            JobPostingAdminController.saveJobPosting(badDatesPayload);
            System.assert(false, 'Expected date validation exception');
        } catch (AuraHandledException e) {
            System.assertNotEquals(null, e.getMessage());
        }

        Boolean nlpHandled = false;
        try {
            JobPostingAdminController.createJobFromNLP('Need an ER nurse in Austin');
            nlpHandled = true;
        } catch (AuraHandledException e) {
            nlpHandled = true;
        }
        System.assertEquals(true, nlpHandled);

        Boolean csvHandled = false;
        try {
            JobPostingAdminController.createJobsFromCSV(null);
            csvHandled = true;
        } catch (AuraHandledException e) {
            csvHandled = true;
        }
        System.assertEquals(true, csvHandled);

        String geminiResult = JobPostingAdminController.testGeminiConnection();
        System.assertNotEquals(null, geminiResult);
    }
}