force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>verified</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Screened</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Offer Accepted - Compliance Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Skill__c/Clinical_Skill__c.object-meta.xml
<CustomObject>
    <label>Clinical Skill</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinical Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinical_Skill__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Clinical Skills</relationshipLabel>
    <relationshipName>Clinical_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Educations</relationshipLabel>
    <relationshipName>Educations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Application_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Certification_Requirement__c/Job_Certification_Requirement__c.object-meta.xml
<CustomObject>
    <label>Certification Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Certification Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Certification Requirements</relationshipLabel>
    <relationshipName>Certification_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/Job_Clinical_Skill__c.object-meta.xml
<CustomObject>
    <label>Job_Clinical_Skill</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Clinical_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Clinical_Skill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Clinical_Skill</relationshipLabel>
    <relationshipName>Job_Clinical_Skill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Education_Requirement__c/Job_Education_Requirement__c.object-meta.xml
<CustomObject>
    <label>Education Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Education Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Education_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Education Requirements</relationshipLabel>
    <relationshipName>Education_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/Job_License_Requirement__c.object-meta.xml
<CustomObject>
    <label>License Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_License_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>License Requirements</relationshipLabel>
    <relationshipName>License_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job_Posting</label>
    <nameField>
        <label>Job_Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Job Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Max_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Max_Experience_Years__c</fullName>
    <label>Max Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Min_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Min_Experience_Years__c</fullName>
    <label>Min Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/Job_Procedure_Requirement__c.object-meta.xml
<CustomObject>
    <label>Job_Procedure_Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Procedure_Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Procedure_Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Procedure_Requirements</relationshipLabel>
    <relationshipName>Job_Procedure_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/License_Certification__c/License_Certification__c.object-meta.xml
<CustomObject>
    <label>License/Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License/Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Certification__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>License/Certifications</relationshipLabel>
    <relationshipName>License_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <label>Procedure</label>
    <nameField>
        <label>Procedure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Procedures</relationshipLabel>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/Technical_Skill__c.object-meta.xml
<CustomObject>
    <label>Technical Skill</label>
    <nameField>
        <label>Technical Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Skill__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Technical Skills</relationshipLabel>
    <relationshipName>Technical_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <label>Work Experience</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Work Experiences</relationshipLabel>
    <relationshipName>Work_Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EligibilityAICallerTest.cls
@IsTest
private class EligibilityAICallerTest {
    private class EligibilityMock implements HttpCalloutMock {
        private String responseBody;
        private Integer code;

        EligibilityMock(String responseBody, Integer code) {
            this.responseBody = responseBody;
            this.code = code;
        }

        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(code);
            res.setBody(responseBody);
            return res;
        }
    }

    private class RetryMock implements HttpCalloutMock {
        private Integer callCount = 0;

        public HttpResponse respond(HttpRequest req) {
            callCount++;
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);

            if (callCount == 1) {
                res.setBody('{"candidates":[{"content":{"parts":[{"text":"not-a-json"}]}}]}');
            } else {
                res.setBody('{"candidates":[{"content":{"parts":[{"text":"```json {\\"eligibilityScore\\":78,\\"summary\\":\\"Good fit\\",\\"pros\\":\\"Strong skills\\",\\"cons\\":\\"Minor gap\\"} ```"}]}}]}');
            }
            return res;
        }
    }

    private static Candidate__c createCandidate() {
        Candidate__c c = new Candidate__c(
            Full_Name__c = 'Eligibility Candidate',
            Email__c = 'eligibility.candidate@example.com'
        );
        insert c;
        return c;
    }

    private static Job_Posting__c createJobPosting() {
        Job_Posting__c jp = new Job_Posting__c(
            Name = 'Eligibility Job',
            Job_Title__c = 'Cardiology Specialist',
            Description__c = 'Cardiology role',
            Min_Experience_Years__c = 2,
            Max_Experience_Years__c = 8
        );
        insert jp;
        return jp;
    }

    private static Job_Application__c createJobApplication(Id candidateId, Id jobPostingId) {
        Job_Application__c app = new Job_Application__c(
            Candidate__c = candidateId,
            Job_Posting__c = jobPostingId,
            Application_Date__c = Date.today(),
            Status__c = 'Application Received'
        );
        insert app;
        return app;
    }

    private static void createRequirementsAndQualifications(Id candidateId, Id jobPostingId) {
        insert new Job_Education_Requirement__c(Job_Posting__c = jobPostingId, Degree_Name__c = 'MBBS', Mandatory__c = true);
        insert new Job_License_Requirement__c(Job_Posting__c = jobPostingId, License_Name__c = 'State License');
        insert new Job_Certification_Requirement__c(Job_Posting__c = jobPostingId, Certification_Name__c = 'ACLS', Mandatory__c = true);
        insert new Job_Clinical_Skill__c(Job_Posting__c = jobPostingId, Skill_Name__c = 'Critical Care', Skill_Level__c = 'Advanced', Mandatory__c = true);
        insert new Job_Procedure_Requirement__c(Job_Posting__c = jobPostingId, Procedure_Name__c = 'Intubation', Critical__c = true);

        insert new Education__c(Candidate__c = candidateId, Degree__c = 'MBBS', Institution__c = 'Med U');
        insert new License_Certification__c(Candidate__c = candidateId, Name = 'State License');
        insert new Clinical_Skill__c(Candidate__c = candidateId, Name = 'Critical Care');
        insert new Technical_Skill__c(Candidate__c = candidateId, Name = 'EHR');
        insert new Work_Experience__c(Candidate__c = candidateId, Role__c = 'Resident', Organization__c = 'City Hospital');
        insert new Procedure__c(Candidate__c = candidateId, Name = 'Intubation');
    }

    @IsTest
    static void testInvocableAndAsyncSuccessPath() {
        Candidate__c candidate = createCandidate();
        Job_Posting__c job = createJobPosting();
        Job_Application__c app = createJobApplication(candidate.Id, job.Id);
        createRequirementsAndQualifications(candidate.Id, job.Id);

        String successBody =
            '{"candidates":[{"content":{"parts":[{"text":"{\\"eligibilityScore\\":85,\\"summary\\":\\"Strong match\\",\\"pros\\":\\"Good experience\\",\\"cons\\":\\"None major\\"}"}]}}]}';

        Test.setMock(HttpCalloutMock.class, new EligibilityMock(successBody, 200));

        EligibilityAICaller.FlowInput input = new EligibilityAICaller.FlowInput();
        input.jobApplicationId = app.Id;

        Test.startTest();
        List<EligibilityAICaller.FlowOutput> outList =
            EligibilityAICaller.callEligibilityAIFromFlow(new List<EligibilityAICaller.FlowInput>{ input });
        Test.stopTest();

        Job_Application__c updated = [
            SELECT Eligibility_Score__c, Eligibility_Summary__c, Eligibility_Pros__c, Eligibility_Cons__c, Status__c
            FROM Job_Application__c
            WHERE Id = :app.Id
        ];

        System.assertEquals(1, outList.size());
        System.assertEquals(true, outList[0].success);
        System.assertNotEquals(null, updated.Status__c, 'Record should remain queryable after async run.');
    }

    @IsTest
    static void testAsyncFailThresholdAndRetryPath() {
        Candidate__c candidate = createCandidate();
        Job_Posting__c job = createJobPosting();
        Job_Application__c app = createJobApplication(candidate.Id, job.Id);
        createRequirementsAndQualifications(candidate.Id, job.Id);

        String lowScoreBody =
            '{"candidates":[{"content":{"parts":[{"text":"{\\"eligibilityScore\\":55,\\"summary\\":\\"Insufficient fit\\",\\"pros\\":\\"Basic education\\",\\"cons\\":\\"Missing depth\\"}"}]}}]}';

        Test.setMock(HttpCalloutMock.class, new EligibilityMock(lowScoreBody, 200));

        Test.startTest();
        EligibilityAICaller.callEligibilityAIAsync(app.Id);
        Test.stopTest();

        Job_Application__c updatedLow = [
            SELECT Eligibility_Score__c, Status__c
            FROM Job_Application__c
            WHERE Id = :app.Id
        ];
        System.assertNotEquals(null, updatedLow.Status__c);
    }

    @IsTest
    static void testAsyncRetryPath() {
        Candidate__c candidate = createCandidate();
        Job_Posting__c job = createJobPosting();
        Job_Application__c appRetry = createJobApplication(candidate.Id, job.Id);
        createRequirementsAndQualifications(candidate.Id, job.Id);
        Test.setMock(HttpCalloutMock.class, new RetryMock());

        Test.startTest();
        EligibilityAICaller.callEligibilityAIAsync(appRetry.Id);
        Test.stopTest();

        Job_Application__c updatedRetry = [
            SELECT Eligibility_Score__c, Status__c
            FROM Job_Application__c
            WHERE Id = :appRetry.Id
        ];

        System.assertNotEquals(null, updatedRetry.Status__c);
    }

    @IsTest
    static void testAsyncHandlesInvalidIdsGracefully() {
        Test.startTest();
        EligibilityAICaller.callEligibilityAIAsync('a0B000000000001AAA');
        List<EligibilityAICaller.FlowOutput> emptyOutput =
            EligibilityAICaller.callEligibilityAIFromFlow(new List<EligibilityAICaller.FlowInput>());
        Test.stopTest();

        System.assertEquals(0, emptyOutput.size());
    }
}