force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Primary role of the candidate used for PHI access and compliance rules.</description>
    <label>Primary Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>Physician</fullName>
            </value>
            <value>
                <fullName>Billing Staff</fullName>
            </value>
            <value>
                <fullName>Medical Officer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Skill__c/Clinical_Skill__c.object-meta.xml
<CustomObject>
    <label>Clinical Skill</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinical Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinical_Skill__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Clinical Skills</relationshipLabel>
    <relationshipName>Clinical_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clinical_Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <label>Skill Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Clinical</fullName>
            </value>
            <value>
                <fullName>Soft</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Certification_Requirement__c/Job_Certification_Requirement__c.object-meta.xml
<CustomObject>
    <label>Certification Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Certification Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Certification_Name__c.field-meta.xml
<CustomField>
    <fullName>Certification_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Certification_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Certification Requirements</relationshipLabel>
    <relationshipName>Certification_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/Job_Clinical_Skill__c.object-meta.xml
<CustomObject>
    <label>Job_Clinical_Skill</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Clinical_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Clinical_Skill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Clinical_Skill</relationshipLabel>
    <relationshipName>Job_Clinical_Skill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Skill_Name__c.field-meta.xml
<CustomField>
    <fullName>Skill_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Skill_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/Job_License_Requirement__c.object-meta.xml
<CustomObject>
    <label>License Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_License_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>License Requirements</relationshipLabel>
    <relationshipName>License_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>License_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job_Posting</label>
    <nameField>
        <label>Job_Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Job Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Max_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Max_Experience_Years__c</fullName>
    <label>Max Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Min_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Min_Experience_Years__c</fullName>
    <label>Min Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <label>Role Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Paramedic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/Job_Procedure_Requirement__c.object-meta.xml
<CustomObject>
    <label>Job_Procedure_Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Procedure_Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Procedure_Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Procedure_Requirements</relationshipLabel>
    <relationshipName>Job_Procedure_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/License_Certification__c/License_Certification__c.object-meta.xml
<CustomObject>
    <label>License/Certification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License/Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License_Certification__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>License/Certifications</relationshipLabel>
    <relationshipName>License_Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License_Certification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <label>Procedure</label>
    <nameField>
        <label>Procedure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Procedures</relationshipLabel>
    <relationshipName>Procedures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Procedure__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Diagnostic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/Technical_Skill__c.object-meta.xml
<CustomObject>
    <label>Technical Skill</label>
    <nameField>
        <label>Technical Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Skill__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Technical Skills</relationshipLabel>
    <relationshipName>Technical_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMR/EHR</fullName>
            </value>
            <value>
                <fullName>PACS</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <label>Work Experience</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Work Experiences</relationshipLabel>
    <relationshipName>Work_Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateJobMatcherControllerTest.cls
@IsTest
private class CandidateJobMatcherControllerTest {
    private static Candidate__c makeCandidate() {
        Candidate__c c = new Candidate__c(
            Full_Name__c = 'AI Match Candidate',
            Email__c = 'aimatch.candidate@example.com',
            Location__c = 'Austin, Texas',
            Years_of_Experience__c = 5
        );
        insert c;

        insert new Work_Experience__c(
            Candidate__c = c.Id,
            Role__c = 'Nurse',
            Organization__c = 'City Hospital'
        );

        insert new License_Certification__c(
            Candidate__c = c.Id,
            Name = 'RN License',
            Type__c = 'License'
        );

        insert new License_Certification__c(
            Candidate__c = c.Id,
            Name = 'BLS',
            Type__c = 'Certification'
        );

        insert new Clinical_Skill__c(
            Candidate__c = c.Id,
            Name = 'Critical Care',
            Skill_Type__c = 'Clinical'
        );

        insert new Procedure__c(
            Candidate__c = c.Id,
            Name = 'IV Cannulation',
            Category__c = 'Emergency'
        );

        insert new Technical_Skill__c(
            Candidate__c = c.Id,
            Name = 'EHR',
            Category__c = 'Software'
        );

        return c;
    }

    private static Job_Posting__c makeJob(String name, String role, Decimal minExp, Decimal maxExp, String city) {
        Job_Posting__c job = new Job_Posting__c(
            Name = name,
            Job_Title__c = name,
            Role_Type__c = role,
            Min_Experience_Years__c = minExp,
            Max_Experience_Years__c = maxExp,
            City__c = city,
            State__c = 'Texas',
            Country__c = 'USA'
        );
        insert job;
        return job;
    }

    @IsTest
    static void testAllJobPostingsAndMatchedJobs() {
        Candidate__c candidate = makeCandidate();

        Job_Posting__c goodJob = makeJob('ICU RN', 'Nurse', 3, 7, 'Austin');
        Job_Posting__c weakJob = makeJob('Remote Pharmacist', 'Pharmacist', 8, 12, 'Boston');

        insert new Job_License_Requirement__c(Job_Posting__c = goodJob.Id, License_Name__c = 'RN License');
        insert new Job_Certification_Requirement__c(Job_Posting__c = goodJob.Id, Certification_Name__c = 'BLS', Mandatory__c = true);
        insert new Job_Clinical_Skill__c(Job_Posting__c = goodJob.Id, Skill_Name__c = 'Critical Care', Skill_Level__c = 'Advanced', Mandatory__c = true);
        insert new Job_Procedure_Requirement__c(Job_Posting__c = goodJob.Id, Procedure_Name__c = 'IV Cannulation', Critical__c = true);

        insert new Job_License_Requirement__c(Job_Posting__c = weakJob.Id, License_Name__c = 'Pharmacist License');

        Test.startTest();
        List<Job_Posting__c> allJobs = CandidateJobMatcherController.getAllJobPostings();
        List<CandidateJobMatcherController.JobMatchResult> matches = CandidateJobMatcherController.getAiMatchedJobs(candidate.Id, 10);
        Test.stopTest();

        System.assert(allJobs.size() >= 2, 'Expected job postings to be returned.');
        System.assert(matches.size() > 0, 'Expected at least one matched job.');
        System.assertEquals(goodJob.Id, matches[0].jobPosting.Id, 'Best matched job should rank first.');
        System.assert(matches[0].matchScore > 0, 'Top match should have positive score.');
        System.assert(matches[0].reasons != null && !matches[0].reasons.isEmpty(), 'Reasons should be returned for explainability.');
    }

    @IsTest
    static void testMatchedJobsNullCandidateThrows() {
        Boolean threw = false;
        try {
            CandidateJobMatcherController.getAiMatchedJobs(null, 10);
        } catch (AuraHandledException e) {
            threw = true;
        }
        System.assertEquals(true, threw, 'Expected exception for null candidate id.');
    }
}