force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Interested_In_Job__c.field-meta.xml
<CustomField>
    <fullName>Interested_In_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interested In Job</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateTriggerHandler1.cls
public with sharing class CandidateTriggerHandler1 {
    // public static void handleAfterUpdate(List<Candidate__c> newCandidates, Map<Id, Candidate__c> oldMap) {
    //     Set<Id> candidateIdsToEvaluate = new Set<Id>();
    //     for (Candidate__c newCand : newCandidates) {
    //         Id oldJobId = (oldMap == null) ? null : oldMap.get(newCand.Id).Interested_In_Job__c;
    //         if (newCand.Interested_In_Job__c != null && newCand.Interested_In_Job__c != oldJobId) {
    //             candidateIdsToEvaluate.add(newCand.Id);
    //         }
    //     }
        
    //     if (!candidateIdsToEvaluate.isEmpty()) {
    //         System.enqueueJob(new ScreeningQueueable(new List<Id>(candidateIdsToEvaluate)));
    //     }
    // }
}