force-app/main/default/objects/Clinical_Skill__c/Clinical_Skill__c.object-meta.xml
<CustomObject>
    <label>Clinical Skill</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinical Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clinical_Skill__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Clinical Skills</relationshipLabel>
    <relationshipName>Clinical_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Certification_Requirement__c/Job_Certification_Requirement__c.object-meta.xml
<CustomObject>
    <label>Certification Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Certification Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Certification_Name__c.field-meta.xml
<CustomField>
    <fullName>Certification_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Certification_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Certification_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Certification Requirements</relationshipLabel>
    <relationshipName>Certification_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/Job_Clinical_Skill__c.object-meta.xml
<CustomObject>
    <label>Job_Clinical_Skill</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Clinical_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Clinical_Skill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Clinical_Skill</relationshipLabel>
    <relationshipName>Job_Clinical_Skill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Clinical_Skill__c/fields/Skill_Name__c.field-meta.xml
<CustomField>
    <fullName>Skill_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Skill_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/Job_License_Requirement__c.object-meta.xml
<CustomObject>
    <label>License Requirements</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>License Requirements Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_License_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>License Requirements</relationshipLabel>
    <relationshipName>License_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_License_Requirement__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>License_Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job_Posting</label>
    <nameField>
        <label>Job_Posting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>ICU</fullName>
            </value>
            <value>
                <fullName>Lab</fullName>
            </value>
            <value>
                <fullName>OPD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Facility Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <formula>IF(
  AND(
    TODAY() &gt;= Start_Date__c,
    TODAY() &lt;= End_Date__c
  ),
  &quot;Open&quot;,
  &quot;Closed&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Job Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Max_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Max_Experience_Years__c</fullName>
    <label>Max Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Min_Experience_Years__c.field-meta.xml
<CustomField>
    <fullName>Min_Experience_Years__c</fullName>
    <label>Min Experience (Years)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Role_Type__c.field-meta.xml
<CustomField>
    <fullName>Role_Type__c</fullName>
    <label>Role Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Paramedic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Shift_Type__c.field-meta.xml
<CustomField>
    <fullName>Shift_Type__c</fullName>
    <label>Shift Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Night</fullName>
            </value>
            <value>
                <fullName>Rotational</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/Job_Procedure_Requirement__c.object-meta.xml
<CustomObject>
    <label>Job_Procedure_Requirement</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job_Procedure_Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Procedure_Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <label>Job_Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job_Procedure_Requirements</relationshipLabel>
    <relationshipName>Job_Procedure_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Procedure_Requirement__c/fields/Procedure_Name__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Procedure_Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Procedure__c/Procedure__c.object-meta.xml
<CustomObject>
    <label>Procedure</label>
    <nameField>
        <label>Procedure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Procedure__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Diagnostic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Technical_Skill__c/Technical_Skill__c.object-meta.xml
<CustomObject>
    <label>Technical Skill</label>
    <nameField>
        <label>Technical Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technical Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technical_Skill__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMR/EHR</fullName>
            </value>
            <value>
                <fullName>PACS</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Experience__c/Work_Experience__c.object-meta.xml
<CustomObject>
    <label>Work Experience</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OPD</fullName>
            </value>
            <value>
                <fullName>ICU</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>Ward</fullName>
            </value>
            <value>
                <fullName>Diagnostics</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CandidateJobMatcherController.cls
public with sharing class CandidateJobMatcherController {

    public class JobMatchResult implements Comparable {
        @AuraEnabled public Job_Posting__c jobPosting;
        @AuraEnabled public Decimal matchScore;
        @AuraEnabled public String scoreLabel;
        @AuraEnabled public List<String> reasons;

        public Integer compareTo(Object otherObj) {
            JobMatchResult other = (JobMatchResult) otherObj;
            Decimal left = this.matchScore == null ? 0 : this.matchScore;
            Decimal right = other.matchScore == null ? 0 : other.matchScore;
            if (left == right) return 0;
            return left > right ? -1 : 1;
        }
    }

    private class CandidateSnapshot {
        public Decimal yearsOfExperience;
        public String location;
        public Set<String> roles = new Set<String>();
        public Set<String> allSkills = new Set<String>();
        public Set<String> clinicalSkills = new Set<String>();
        public Set<String> credentials = new Set<String>();
        public Boolean hasResume = false;
    }

    @AuraEnabled(cacheable=true)
    public static List<Job_Posting__c> getAllJobPostings() {
        return [
            SELECT Id, Name, Job_Title__c, Description__c, Category__c, Department__c,
                   Role_Type__c, Employment_Type__c, Shift_Type__c,
                   Min_Experience_Years__c, Max_Experience_Years__c,
                   Facility_Name__c, City__c, State__c, Country__c,
                   Start_Date__c, End_Date__c, Job_Status__c, CreatedDate
            FROM Job_Posting__c
            ORDER BY CreatedDate DESC
            LIMIT 200
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<JobMatchResult> getAiMatchedJobs(Id candidateId, Integer maxResults) {
        if (candidateId == null) {
            throw new AuraHandledException('Candidate ID is required.');
        }

        Integer safeLimit = (maxResults == null || maxResults <= 0) ? 25 : Math.min(maxResults, 100);

        CandidateSnapshot candidate = buildCandidateSnapshot(candidateId);
        if (!isCandidateEligibleForMatching(candidate)) {
            return new List<JobMatchResult>();
        }
        List<Job_Posting__c> jobs = getAllJobPostings();

        if (jobs.isEmpty()) {
            return new List<JobMatchResult>();
        }

        Set<Id> jobIds = new Set<Id>();
        for (Job_Posting__c job : jobs) {
            jobIds.add(job.Id);
        }

        Map<Id, Set<String>> jobLicenses = new Map<Id, Set<String>>();
        Map<Id, Set<String>> jobCertifications = new Map<Id, Set<String>>();
        Map<Id, Set<String>> jobClinicalSkills = new Map<Id, Set<String>>();
        Map<Id, Set<String>> jobProcedures = new Map<Id, Set<String>>();

        for (Job_License_Requirement__c item : [
            SELECT Job_Posting__c, License_Name__c
            FROM Job_License_Requirement__c
            WHERE Job_Posting__c IN :jobIds
        ]) {
            addToJobRequirementMap(jobLicenses, item.Job_Posting__c, item.License_Name__c);
        }

        for (Job_Certification_Requirement__c item : [
            SELECT Job_Posting__c, Certification_Name__c
            FROM Job_Certification_Requirement__c
            WHERE Job_Posting__c IN :jobIds
        ]) {
            addToJobRequirementMap(jobCertifications, item.Job_Posting__c, item.Certification_Name__c);
        }

        for (Job_Clinical_Skill__c item : [
            SELECT Job_Posting__c, Skill_Name__c
            FROM Job_Clinical_Skill__c
            WHERE Job_Posting__c IN :jobIds
        ]) {
            addToJobRequirementMap(jobClinicalSkills, item.Job_Posting__c, item.Skill_Name__c);
        }

        for (Job_Procedure_Requirement__c item : [
            SELECT Job_Posting__c, Procedure_Name__c
            FROM Job_Procedure_Requirement__c
            WHERE Job_Posting__c IN :jobIds
        ]) {
            addToJobRequirementMap(jobProcedures, item.Job_Posting__c, item.Procedure_Name__c);
        }

        List<JobMatchResult> scored = new List<JobMatchResult>();

        for (Job_Posting__c job : jobs) {
            JobMatchResult result = scoreJob(
                job,
                candidate,
                jobLicenses.get(job.Id),
                jobCertifications.get(job.Id),
                jobClinicalSkills.get(job.Id),
                jobProcedures.get(job.Id)
            );

            if (result.matchScore > 0) {
                scored.add(result);
            }
        }

        scored.sort();
        if (scored.size() > safeLimit) {
            List<JobMatchResult> trimmed = new List<JobMatchResult>();
            for (Integer i = 0; i < safeLimit; i++) {
                trimmed.add(scored[i]);
            }
            scored = trimmed;
        }
        return scored;
    }

    private static CandidateSnapshot buildCandidateSnapshot(Id candidateId) {
        Candidate__c candidate = [
            SELECT Id, Location__c, Years_of_Experience__c
            FROM Candidate__c
            WHERE Id = :candidateId
            LIMIT 1
        ];

        CandidateSnapshot snapshot = new CandidateSnapshot();
        snapshot.location = candidate.Location__c;
        snapshot.yearsOfExperience = candidate.Years_of_Experience__c;

        for (Work_Experience__c work : [
            SELECT Role__c
            FROM Work_Experience__c
            WHERE Candidate__c = :candidateId
        ]) {
            if (String.isNotBlank(work.Role__c)) {
                snapshot.roles.add(normalize(work.Role__c));
            }
        }

        for (Clinical_Skill__c skill : [
            SELECT Name
            FROM Clinical_Skill__c
            WHERE Candidate__c = :candidateId
        ]) {
            String normalized = normalize(skill.Name);
            if (String.isNotBlank(normalized)) {
                snapshot.clinicalSkills.add(normalized);
                snapshot.allSkills.add(normalized);
            }
        }

        for (Technical_Skill__c skill : [
            SELECT Name
            FROM Technical_Skill__c
            WHERE Candidate__c = :candidateId
        ]) {
            String normalized = normalize(skill.Name);
            if (String.isNotBlank(normalized)) {
                snapshot.allSkills.add(normalized);
            }
        }

        for (Procedure__c item : [
            SELECT Name
            FROM Procedure__c
            WHERE Candidate__c = :candidateId
        ]) {
            String normalized = normalize(item.Name);
            if (String.isNotBlank(normalized)) {
                snapshot.allSkills.add(normalized);
            }
        }

        for (License_Certification__c item : [
            SELECT Name
            FROM License_Certification__c
            WHERE Candidate__c = :candidateId
        ]) {
            String normalized = normalize(item.Name);
            if (String.isNotBlank(normalized)) {
                snapshot.credentials.add(normalized);
            }
        }

        // Detect whether candidate has uploaded a likely resume file.
        Integer resumeCount = [
            SELECT COUNT()
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :candidateId
            AND ContentDocument.FileType IN ('PDF', 'WORD_X', 'WORD')
        ];
        snapshot.hasResume = resumeCount > 0;

        return snapshot;
    }

    private static JobMatchResult scoreJob(
        Job_Posting__c job,
        CandidateSnapshot candidate,
        Set<String> licenseReqs,
        Set<String> certificationReqs,
        Set<String> clinicalReqs,
        Set<String> procedureReqs
    ) {
        Decimal score = 0;
        List<String> reasons = new List<String>();
        Boolean hasRealMatch = false;

        String normalizedJobRole = normalize(job.Role_Type__c);
        if (String.isNotBlank(normalizedJobRole)) {
            if (candidate.roles.contains(normalizedJobRole)) {
                score += 30;
                reasons.add('Role alignment: direct match for ' + job.Role_Type__c);
                hasRealMatch = true;
            } else if (hasTokenOverlap(candidate.roles, normalizedJobRole)) {
                score += 15;
                reasons.add('Role alignment: partial role overlap');
                hasRealMatch = true;
            }
        }

        score += scoreExperience(candidate.yearsOfExperience, job.Min_Experience_Years__c, job.Max_Experience_Years__c, reasons);
        if (scoreLocation(candidate.location, job.City__c, job.State__c, job.Country__c, reasons) > 0) {
            hasRealMatch = true;
            score += 10;
        }

        Set<String> requiredSkills = (procedureReqs == null) ? new Set<String>() : procedureReqs;
        Decimal skillsScore = scoreRatio(requiredSkills, candidate.allSkills, 20, 'Required skills', reasons);
        score += skillsScore;
        if (requiredSkills != null && !requiredSkills.isEmpty() && countNormalizedMatches(requiredSkills, candidate.allSkills) > 0) {
            hasRealMatch = true;
        }

        Set<String> requiredClinical = (clinicalReqs == null) ? new Set<String>() : clinicalReqs;
        Decimal clinicalScore = scoreRatio(requiredClinical, candidate.clinicalSkills, 10, 'Clinical skills', reasons);
        score += clinicalScore;
        if (requiredClinical != null && !requiredClinical.isEmpty() && countNormalizedMatches(requiredClinical, candidate.clinicalSkills) > 0) {
            hasRealMatch = true;
        }

        Set<String> requiredCredentials = new Set<String>();
        if (licenseReqs != null) requiredCredentials.addAll(licenseReqs);
        if (certificationReqs != null) requiredCredentials.addAll(certificationReqs);
        Decimal credentialScore = scoreRatio(requiredCredentials, candidate.credentials, 15, 'Certifications/Licenses', reasons);
        score += credentialScore;
        if (!requiredCredentials.isEmpty() && countNormalizedMatches(requiredCredentials, candidate.credentials) > 0) {
            hasRealMatch = true;
        }

        if (!hasRealMatch) {
            JobMatchResult noMatch = new JobMatchResult();
            noMatch.jobPosting = job;
            noMatch.matchScore = 0;
            noMatch.scoreLabel = 'Low';
            noMatch.reasons = new List<String>{ 'No direct skill/role/location/credential match.' };
            return noMatch;
        }

        JobMatchResult result = new JobMatchResult();
        result.jobPosting = job;
        result.matchScore = score.setScale(2);
        result.scoreLabel = getScoreLabel(result.matchScore);
        result.reasons = reasons;
        return result;
    }

    private static Decimal scoreExperience(Decimal candidateExp, Decimal minExp, Decimal maxExp, List<String> reasons) {
        if (minExp == null && maxExp == null) {
            reasons.add('Experience: no minimum/maximum restriction');
            return 15;
        }

        if (candidateExp == null) {
            return 0;
        }

        Decimal minVal = (minExp == null) ? 0 : minExp;
        Decimal maxVal = (maxExp == null) ? 999 : maxExp;

        if (candidateExp >= minVal && candidateExp <= maxVal) {
            reasons.add('Experience: within required range (' + String.valueOf(minVal) + '-' + String.valueOf(maxVal) + ' years)');
            return 15;
        }

        if ((candidateExp + 1) >= minVal && (candidateExp - 1) <= maxVal) {
            reasons.add('Experience: close to required range');
            return 7;
        }

        return 0;
    }

    private static Decimal scoreLocation(String candidateLocation, String city, String state, String country, List<String> reasons) {
        String candidateLoc = normalize(candidateLocation);
        if (String.isBlank(candidateLoc)) {
            return 0;
        }

        List<String> jobLocations = new List<String>{ city, state, country };
        for (String value : jobLocations) {
            String normalized = normalize(value);
            if (String.isNotBlank(normalized) && (candidateLoc.contains(normalized) || normalized.contains(candidateLoc))) {
                reasons.add('Location compatibility: ' + value);
                return 10;
            }
        }
        return 0;
    }

    private static Decimal scoreRatio(Set<String> required, Set<String> candidateSet, Decimal maxPoints, String factorName, List<String> reasons) {
        if (required == null || required.isEmpty()) {
            reasons.add(factorName + ': no mandatory requirements defined (0 points)');
            return 0;
        }

        Integer matched = countNormalizedMatches(required, candidateSet);

        Decimal value = (Decimal.valueOf(matched) / required.size()) * maxPoints;
        reasons.add(factorName + ': matched ' + matched + ' of ' + required.size());
        return value;
    }

    private static Integer countNormalizedMatches(Set<String> required, Set<String> candidateSet) {
        if (required == null || required.isEmpty() || candidateSet == null || candidateSet.isEmpty()) {
            return 0;
        }

        Integer matched = 0;
        for (String req : required) {
            if (containsNormalized(candidateSet, req)) {
                matched++;
            }
        }
        return matched;
    }

    private static Boolean isCandidateEligibleForMatching(CandidateSnapshot snapshot) {
        if (snapshot == null) return false;
        Boolean hasSkills = snapshot.allSkills != null && !snapshot.allSkills.isEmpty();
        Boolean hasExperience = (snapshot.yearsOfExperience != null) || (snapshot.roles != null && !snapshot.roles.isEmpty());

        // Hard gate: if no resume + no skills + no experience, do not return matches.
        if (!snapshot.hasResume && !hasSkills && !hasExperience) {
            return false;
        }
        return true;
    }

    private static Boolean containsNormalized(Set<String> values, String requirement) {
        String req = normalize(requirement);
        if (String.isBlank(req) || values == null || values.isEmpty()) {
            return false;
        }

        if (values.contains(req)) {
            return true;
        }

        for (String value : values) {
            if (value.contains(req) || req.contains(value)) {
                return true;
            }
        }

        return false;
    }

    private static Boolean hasTokenOverlap(Set<String> candidateRoles, String jobRole) {
        if (candidateRoles == null || candidateRoles.isEmpty() || String.isBlank(jobRole)) {
            return false;
        }

        Set<String> jobTokens = toTokens(jobRole);
        if (jobTokens.isEmpty()) {
            return false;
        }

        for (String role : candidateRoles) {
            Set<String> roleTokens = toTokens(role);
            Set<String> overlap = new Set<String>(jobTokens);
            overlap.retainAll(roleTokens);
            if (!overlap.isEmpty()) {
                return true;
            }
        }

        return false;
    }

    private static Set<String> toTokens(String value) {
        Set<String> tokens = new Set<String>();
        String normalized = normalize(value);
        if (String.isBlank(normalized)) {
            return tokens;
        }

        for (String token : normalized.split(' ')) {
            if (String.isNotBlank(token)) {
                tokens.add(token);
            }
        }

        return tokens;
    }

    private static void addToJobRequirementMap(Map<Id, Set<String>> target, Id jobId, String rawValue) {
        if (jobId == null) return;

        String normalized = normalize(rawValue);
        if (String.isBlank(normalized)) return;

        if (!target.containsKey(jobId)) {
            target.put(jobId, new Set<String>());
        }
        target.get(jobId).add(normalized);
    }

    private static String normalize(String input) {
        if (String.isBlank(input)) return '';
        return input.toLowerCase().trim().replaceAll('[^a-z0-9\\s]', ' ').replaceAll('\\s+', ' ');
    }

    private static String getScoreLabel(Decimal score) {
        Decimal val = score == null ? 0 : score;
        if (val >= 80) return 'Excellent';
        if (val >= 60) return 'Good';
        if (val >= 40) return 'Fair';
        return 'Low';
    }
}